# Generated by Django 4.1 on 2023-02-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_options_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AmountIngredient',
            new_name='RecipeIngredient',
        ),
    ]
